#!/usr/bin/env bash
set -euo pipefail

in_file="${1:-coverage.raw.out}"
out_file="${2:-coverage.out}"

if [[ ! -f "$in_file" ]]; then
  echo "coverage input not found: $in_file" >&2
  exit 1
fi

module_path="$(go list -m -f '{{.Path}}')"
tmp_excludes="$(mktemp)"
trap 'rm -f "$tmp_excludes"' EXIT

is_generated_file() {
  local f="$1"
  local b
  b="$(basename "$f")"

  case "$f" in
    pkg/cypher/antlr/*) return 0 ;;
    pkg/graphql/generated/*) return 0 ;;
  esac

  case "$b" in
    *_gen.go|*.generated.go|zz_generated*.go|generated.go) return 0 ;;
  esac

  if head -n 20 "$f" 2>/dev/null | grep -Eiq \
    'code generated .*do not edit|automatically generated by antlr|automatically regenerated based on the schema|generated by gqlgen'; then
    return 0
  fi

  return 1
}

while IFS= read -r rel; do
  [[ -f "$rel" ]] || continue
  if is_generated_file "$rel"; then
    printf '%s/%s:\n' "$module_path" "$rel" >> "$tmp_excludes"
  fi
done < <(git ls-files '*.go')

awk '
  NR==FNR { ex[$0]=1; next }
  FNR==1 { print; next }
  {
    split($0, p, ":")
    key = p[1] ":"
    if (!(key in ex)) print
  }
' "$tmp_excludes" "$in_file" > "$out_file"
