#!/usr/bin/env bash
set -euo pipefail

in_file="${1:-coverage.raw.out}"
out_file="${2:-coverage.out}"

if [[ ! -f "$in_file" ]]; then
  echo "coverage input not found: $in_file" >&2
  exit 1
fi

module_path="$(go list -m -f '{{.Path}}')"
tmp_excludes="$(mktemp)"
tmp_function_ranges="$(mktemp)"
tmp_stage1="$(mktemp)"
trap 'rm -f "$tmp_excludes" "$tmp_function_ranges" "$tmp_stage1"' EXIT

is_excluded_from_coverage() {
  local f="$1"
  local b
  b="$(basename "$f")"

  case "$f" in
    pkg/cypher/antlr/*) return 0 ;;
    pkg/graphql/generated/*) return 0 ;;
    pkg/gpu/*) return 0 ;;
  esac

  case "$b" in
    *_gen.go|*.generated.go|zz_generated*.go|generated.go) return 0 ;;
    *gpu*.go|*metal*.go|*vulkan*.go|*cuda*.go) return 0 ;;
  esac

  if head -n 20 "$f" 2>/dev/null | grep -Eiq \
    'code generated .*do not edit|automatically generated by antlr|automatically regenerated based on the schema|generated by gqlgen'; then
    return 0
  fi

  return 1
}

while IFS= read -r rel; do
  [[ -f "$rel" ]] || continue
  if is_excluded_from_coverage "$rel"; then
    printf '%s/%s:\n' "$module_path" "$rel" >> "$tmp_excludes"
    continue
  fi

  # Exclude function ranges with hardware-accelerator names even inside mixed files
  # (e.g. ensureGPUIndexSynced in search.go).
  awk -v module_path="$module_path" -v rel="$rel" '
    /^[[:space:]]*func[[:space:]]*(\([^)]*\)[[:space:]]*)?[A-Za-z_][A-Za-z0-9_]*[[:space:]]*\(/ {
      sig = $0
      sub(/^[[:space:]]*func[[:space:]]*/, "", sig)
      if (sig ~ /^\(/) {
        sub(/^\([^)]*\)[[:space:]]*/, "", sig)
      }
      name = sig
      sub(/[[:space:]]*\(.*/, "", name)
      starts[++n] = NR
      names[n] = name
    }
    END {
      for (i = 1; i <= n; i++) {
        lname = tolower(names[i])
        if (lname ~ /gpu|metal|vulkan|cuda/) {
          end = (i < n ? starts[i+1] - 1 : 1000000000)
          printf "%s/%s:%d:%d\n", module_path, rel, starts[i], end
        }
      }
    }
  ' "$rel" >> "$tmp_function_ranges"
done < <(git ls-files '*.go')

# Stage 1: remove whole-file exclusions.
awk '
  NR==FNR { ex[$0]=1; next }
  FNR==1 { print; next }
  {
    split($0, p, ":")
    key = p[1] ":"
    if (!(key in ex)) print
  }
' "$tmp_excludes" "$in_file" > "$tmp_stage1"

# Stage 2: remove function-level excluded ranges.
awk '
  NR==FNR {
    split($0, p, ":")
    if (length(p) >= 3) {
      file = p[1]
      start = p[2] + 0
      finish = p[3] + 0
      ranges[file] = ranges[file] start "-" finish ";"
    }
    next
  }
  FNR==1 { print; next }
  {
    split($1, p, ":")
    file = p[1]
    split(p[2], span, ",")
    split(span[1], startParts, ".")
    split(span[2], endParts, ".")
    segStart = startParts[1] + 0
    segEnd = endParts[1] + 0

    excluded = 0
    if (file in ranges) {
      n = split(ranges[file], rr, ";")
      for (i = 1; i <= n; i++) {
        if (rr[i] == "") {
          continue
        }
        split(rr[i], b, "-")
        rStart = b[1] + 0
        rEnd = b[2] + 0
        if (!(segEnd < rStart || segStart > rEnd)) {
          excluded = 1
          break
        }
      }
    }
    if (!excluded) {
      print
    }
  }
' "$tmp_function_ranges" "$tmp_stage1" > "$out_file"
